# Generated by Django 4.1.3 on 2024-05-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='supplyer_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
