# Generated by Django 4.1.3 on 2024-05-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_supply_supplyer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='supplyer_name',
        ),
        migrations.AddField(
            model_name='supply',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supply',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
