# Generated by Django 4.1.3 on 2024-05-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_buyer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=6),
        ),
    ]
