# Generated by Django 4.1.3 on 2024-05-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0011_mycart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mycart',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
