# Generated by Django 4.1.3 on 2024-05-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0012_mycart_quantity_mycart_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'purchased')], default='pending', max_length=15),
        ),
    ]
